### ISSUE TITLE
Python3.7 has asyncio.run() func now

### ISSUE THREAD

**Issue by chenjiandongx** [cjrh/aiorun#15] opened 2018-08-05 12:35 UTC
the latest python version 3.7 brings asyncio.run() function,it is a great feature

now we cloud use it easily, example
···
import asyncio

async def main():
    await asyncio.sleep(1.0)
    print("hello cjrh!")

asyncio.run(main())
···

And your aiorun is aslso a awesome library.

**Comment by cjrh** [comment] 2018-08-05 23:06
Duplicate of #16

**Closed by cjrh** 2018-08-05 23:06 UTC
