### ISSUE TITLE
Error "If you provide a loop instance...", but I haven't

### ISSUE THREAD

**Issue by gegnew** [cjrh/aiorun#86] opened 2023-09-01 16:04 UTC
I'm getting the "If you provide a loop instance, and you've configured a custom exception handler on it..." error, but I have not configured a custom exception handler.

Surprisingly, I'm getting this with _and_ without the `stop_on_unhandled_errors` arg.

```python
        loop = asyncio.get_event_loop()
        asyncio.set_event_loop(loop)
        run(self.main(), loop=loop)  # happens if this
        # run(self.main(), loop=loop, stop_on_unhandled_errors=True)  # and also this
```

The only "funny" or additional thing is that this code is running in AWS Greengrass, but I don't think this should matter.

Thoughts, or additional info I can provide that might elucidate the problem?

**Comment by cjrh** [comment] 2023-09-01 22:33
Does the problem go away if you don't provide a loop?  Not suggesting you do that, just curious.  Also, is the code example you provided accurate, or do you do anything else with the loop instance you create?  If you could provide a fully self-contained, and preferably short example that I can run and see the error, that would help a lot.

**Comment by cjrh** [comment] 2023-09-03 11:44
I tried to reproduce with the following code example, but I don't get the error like you've described:

```python
# main.py
import asyncio
import aiorun

async def main():
    print("Hello world!")

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    asyncio.set_event_loop(loop)
    aiorun.run(main(), loop=loop)
```

And then running it:

```
$ python main.py 
Hello world!
^CStopping the loop
```

Without a reproducer there is not much I can do. I'll leave this open for a few more days, but eventually I will have to close it.

**Comment by cjrh** [comment] 2023-09-10 21:00
Closing because I can't reproduce, but if you do find a reproducer we can reopen.

**Closed by cjrh** 2023-09-10 21:00 UTC
