### ISSUE TITLE
Add ability for use run_until_complete

### ISSUE THREAD

**Issue by heckad** [cjrh/aiorun#34] opened 2020-01-12 17:37 UTC
If to try to create something(example: connection to rabbitmq) in a main function and it something compleat with an exception then would be nice to exit from an app. Еhis behaviour can be achieved through the use of `run_until_complete` method instead of `run_forever`. Propose to replace method.

**Comment by cjrh** [comment] 2020-01-12 22:53
Hi @heckad 

I added support for this in https://github.com/cjrh/aiorun/commit/ba73ee6d4ade7465a5daba4e287c234c5727228c

There is a new parameter to `aiorun.run()`, called `stop_on_unhandled_errors` that should work the way you describe.  Alternatively, even before this change it was (is) possible for you to catch the exception yourself and stop the loop, for example:

```
import asyncio
import aiorun

async def main():
    try:
        conn = await aiorabbit.connect()
    except:
        print('Problem connecting to rabbitmq, exiting...')
        # Stopping the loop will initiate shutdown procedure.
        asyncio.get_running_loop().stop()

aiorun.run(main())
```

As I explained in #25, I'm a bit worried about changing from `run_forever()` to `run_until_complete()` because it will change the sematics of how aiorun works.  But if everyone wants this change then I'm happy to do that.

**Comment by heckad** [comment] 2020-01-13 08:15
Why do you add 
```
    assert not (loop and stop_on_unhandled_errors), (
        "'loop' and 'stop_on_unhandled_errors' parameters are mutually "
        "exclusive. (If you need custom error handling, set that on your "
        "own loop being provided."
    )
```
In my use case need to freeze loop before making import, because I should use loop and stop_on_unhandled_errors but I can't do this on the reason above. Maybe it’s worth removing the assertion and add warning. Also if use max level of optimization then python will ignore assert!

**Comment by cjrh** [comment] 2020-01-14 12:25
Big thanks for your suggestion to change those assertion checks. They were there from the early days and I just never got around to changing them to exceptions.  Your comment finally got me to look at it so I've changed those checks to not use assertions. (In new version 2020.1.1).

Regarding the mutex on the loop parameter, and `stop_on_unhandled_errors`: it's quite tricky. My thinking is this: if a loop object is supplied, it may have already had a custom exception handler added to it.  If so, I wouldn't want to replace that custom exception handler with a different one, in this case, the one I'm using to manage `stop_on_unhandled_errors`.  

I checked the docs again. It seems that I will be able to check whether a custom exception handler has been set or not, by calling `loop.get_exception_handler()`: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.get_exception_handler

The docs say that this method will return `None` if no custom exception handler has been set.  So I could change my check to look like this:

```
    if loop and loop.get_exception_handler() and stop_on_unhandled_errors:
        raise Exception(
            "'loop' and 'stop_on_unhandled_errors' parameters are mutually "
            "exclusive. (If you need custom error handling, set that on your "
            "own loop being provided.)"
        )
```

This way, if (a) an existing loop was provided, and (b) that loop does not have a custom exception handler configured, then we can proceed to add our own custom exception handler if the `stop_on_unhandled_errors` parameter is `True`.

What do you think @heckad ?

**Comment by cjrh** [comment] 2020-01-14 12:27
The other option is just to give up using `run_forever` completely, and switch to `run_until_complete` like `asyncio.run` is doing.  You're the second person to be surprised that unhandled exceptions don't crash the loop and it makes me think that my default behaviour is too surprising.

**Comment by heckad** [comment] 2020-01-16 08:00
Yes, change on `run_until_complete` like in standard library will be greate.

**Comment by heckad** [comment] 2020-01-16 16:18
Please, add `loop.get_exception_handler()`. It's also needed.

**Comment by cjrh** [comment] 2020-01-16 23:48
Ok, when I have some time available I will 

1. Add the `get_exception_handler()` check to the current code (pretty easy)
2. Explore changing over to `run_until_complete` (probably a lot of work)

**Comment by cjrh** [comment] 2020-01-17 00:34
@heckad I didn't understand your point here:

>  I use aiorun for freeze event loop,

Could you explain a bit more? I'm always interested in the reasons why people are using `aiorun` instead of `asyncio.run`.

**Comment by cjrh** [comment] 2020-01-19 08:26
@heckad I have added the check for `get_exception_hander()` and released a new version of aiorun to PyPI so you should be able to pass in your custom loop instance and specify `stop_on_unhandled_errors` at the same time.

I have also added a new section in the README dealing with such error handling, with code examples: https://github.com/cjrh/aiorun#error-handling

Regarding `run_until_complete()`, I've given it a lot more thought. The `stop_on_unhandled_errors` parameter should give the same error behaviour as using `run_until_complete` (and I've added more text to the opening section of the README to point out the behaviour difference between the standard library `run()` and `aiorun.run()`). So I think we're ok for now.  I don't have resources right now to refactor/change the code to use `run_until_complete()` anyway.  (Maybe someone comes along in the future with a PR).

I'll leave this issue open for a week or so, to give you some time to give me your thoughts.

**Comment by heckad** [comment] 2020-01-19 10:13
If to use `aiorun` this example will work forever

```
import asyncio

import aiorun


async def infinite_task():
    while True:
        await asyncio.sleep(1)


async def task_with_exception():
    await asyncio.sleep(1)
    raise Exception


async def main():
    await asyncio.wait([
        infinite_task(),
        task_with_exception()
    ], return_when=asyncio.FIRST_EXCEPTION)


if __name__ == '__main__':
    # asyncio.run(main())
    aiorun.run(main())
```
If to use builtin run then it compleate and **kubernetes restart it!**

**Comment by cjrh** [comment] 2020-01-19 11:08
Thank you for providing me with an example. I really appreciate it.

In your example, if your intention is to exit after the `asyncio.wait()`, then with `aiorun.run()` you must stop the loop at the end of the `main()` method:

```
import asyncio

import aiorun


async def infinite_task():
    while True:
        await asyncio.sleep(1)


async def task_with_exception():
    await asyncio.sleep(1)
    raise Exception


async def main():
    await asyncio.wait([
        infinite_task(),
        task_with_exception()
    ], return_when=asyncio.FIRST_EXCEPTION)
    asyncio.get_running_loop().stop()


if __name__ == '__main__':
    # asyncio.run(main())
    aiorun.run(main())
```

I tried to explain this in the README, right at the beginning. Maybe my text is not clear enough?

This has nothing to do with exception handling. Keeping the loop running after the starting coroutine returns is (at the moment) by design. Since the beginning, `aiorun.run(main())` continues to run after `main()` exits, and in my changes to the README earlier today, I gave an example where `aiorun.run()` is called even without a starting coroutine. 

One of the use-cases for this feature is to use `main()` merely for setting up other independent tasks but not await them. For example:

```
import asyncio
import aiorun

async def receiver(q: asyncio.Queue):
    while (work := await q.get()):
        <do stuff>

async def producer(q: asyncio.Queue):
    while True:
        work = <get work>
        await q.put(work()

async def main():
    q = asyncio.Queue()
    asyncio.create_task(receiver(q))
    asyncio.create_task(producer(q))

if __name__ == '__main__':
    aiorun.run(main())
```

In this example, `main()` will return after setting up all the other tasks, but the loop will continue to run and allow the other tasks to continue functioning.  If I changed it to automatically stop the loop after `main()` returns, then this kind of program becomes awkward.  Sometimes silly things have to be done, like

```
async def main():
    q = asyncio.Queue()
    asyncio.create_task(receiver(q))
    asyncio.create_task(producer(q))
    await asyncio.sleep(100000)
```

or, more commonly:

```
async def main():
    q = asyncio.Queue()
    t1 = asyncio.create_task(receiver(q))
    t2 = asyncio.create_task(producer(q))
    await asyncio.gather(t1, t2)
```

and so on.   For your use-case will it be sufficient for you to call `loop.stop()` at the end of your `main()` function?

**Comment by cjrh** [comment] 2020-01-27 12:36
I had a look at changing the internal code to use `run_until_complete`. It's quite a lot of work to change. Since (a) there is a now a configuration parameter to stop the loop if an exception is raised, and (b) it is documented that the way to stop the loop when `main()` finishes is by calling `loop.stop()`, I'm going to close this issue.  Someone else might come along and submit a PR that changes the implementation to use `run_until_complete()` instead, but that isn't going to be me.  So for now, I'm closing this issue since there is nothing I can do about it.

**Closed by cjrh** 2020-01-27 12:36 UTC
